config/routes.rb
Rails.application.routes.draw do

  resources :announcements
  resources :messages
  resources :messages
  resources :bills
  
get "/bills/userbill/:apartment_number" => "bills#userbill"

get "/login" => "sessions#new"
post "/login" => "sessions#create"
get "/logout" => "sessions#destroy"

get "/signup" => "users#new"
post "/users" => "users#create"
get "/userslist" => "users#userslist"

get "/homepage" => "misc#homepage"

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_admin, only: [:new, :edit, :create, :update, :destroy]
  before_filter :authorize

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
    @announcements = @announcements.sort_by(&:date_posted).reverse
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.date_posted = DateTime.now

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:subject, :content)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Date posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.subject %></td>
        <td><%= announcement.date_posted %></td>
        <td><%= link_to 'Show', announcement %></td>
        <% if current_user.username == "admin" %><td><%= link_to 'Edit', edit_announcement_path(announcement) %></td><% end %>
        <% if current_user.username == "admin" %><td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.username == "admin" %><%= link_to 'New Announcement', new_announcement_path %><% end %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @announcement.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @announcement.content %>
</p>

<p>
  <strong>Date posted:</strong>
  <%= @announcement.date_posted %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>