config/routes.rb
Rails.application.routes.draw do

  resources :announcements
  resources :messages
  resources :messages
  resources :bills
  
get "/bills/userbill/:apartment_number" => "bills#userbill"

get "/login" => "sessions#new"
post "/login" => "sessions#create"
get "/logout" => "sessions#destroy"

get "/signup" => "users#new"
post "/users" => "users#create"
get "/userslist" => "users#userslist"

get "/homepage" => "misc#homepage"

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  before_filter :authorize_admin, only: [:new, :edit, :create, :update, :destroy]
  
  def userbill	
	@bills = Bill.where(apartment_number: params[:apartment_number])
	render "/bills/index"
  end

  # GET /bills
  # GET /bills.json
  def index
	@current_user ||= User.find(session[:user_id])
	if @current_user.username == "admin"
		@bills = Bill.all
    else
		@bills = Bill.where(apartment_number: @current_user.apartment_number)
	end
	
	@bills = @bills.sort_by(&:due_date).reverse
	
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:apartment_number, :rent, :electricity_bill, :water_bill, :due_date, :status)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apartment_number %><br>
    <%= f.text_field :apartment_number %>
  </div>
  <div class="field">
    <%= f.label :rent %><br>
    <%= f.text_field :rent %>
  </div>
  <div class="field">
    <%= f.label :electricity_bill %><br>
    <%= f.text_field :electricity_bill %>
  </div>
  <div class="field">
    <%= f.label :water_bill %><br>
    <%= f.text_field :water_bill %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ['Payment Pending','Paid'] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bills</h1>

<table>
  <thead>
    <tr>
      <th>Apartment number</th>
      <th>Rent</th>
      <th>Electricity bill</th>
      <th>Water bill</th>
      <th>Due date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.apartment_number %></td>
        <td><%= bill.rent %></td>
        <td><%= bill.electricity_bill %></td>
        <td><%= bill.water_bill %></td>
        <td><%= bill.due_date %></td>
        <td><%= bill.status %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><% if current_user.username == "admin" %><%= link_to 'Edit', edit_bill_path(bill) %><% end %></td>
        <td><% if current_user.username == "admin" %><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.username == "admin" %><%= link_to 'New Bill', new_bill_path %><%end%>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apartment number:</strong>
  <%= @bill.apartment_number %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @bill.rent %>
</p>

<p>
  <strong>Electricity bill:</strong>
  <%= @bill.electricity_bill %>
</p>

<p>
  <strong>Water bill:</strong>
  <%= @bill.water_bill %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @bill.due_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bill.status %>
</p>

<% if current_user.username == "admin" %><%= link_to 'Edit', edit_bill_path(@bill) %> |<% end %>
<%= link_to 'Back', bills_path %>